version: "3.9"
services:
  backend:
    container_name: koicaster
    build: ./
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - ./.env
      
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - ./servers.json:/pgamdin4/servers.json

  db:
    container_name: db
    image: postgres:15.6
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - koicaster-postgress-data:/var/lib/postgresql/data

volumes:
  backend_node_modules:
  koicaster-postgress-data:
